export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_GURUNAVI_DATA = 'GET_GURUNAVI_DATA';

export const PASS_CURRENT_LOCATION = 'PASS_CURRENT_LOCATION';
export const ERROR_CURRENT_LOCATION = 'ERROR_CURRENT_LOCATION';